languageCode = 'ru'
title = 'Леонид Павлов'
disableKinds = ['taxonomy', 'RSS', 'term', '404', 'robotsTXT']
[params]
  RecordingsBaseUrl = 'https://pavlov.photography/leonid-pavlov/audio-aac/'
[permalinks]
  recordings = "/recordings/:filename/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = false
    [markup.goldmark.extensions]
      footnote = true
      [markup.goldmark.extensions.typographer]
        disable = false
      [markup.goldmark.extensions.passthrough]
        # enable = true
        # [markup.goldmark.extensions.passthrough.delimiters]
          # block = [['$$', '$$'], ['\[', '\]']]
          # inline = [['$', '$']]