languageCode = 'ru'
title = 'Стихи - Леонид Павлов'
disableKinds = ['taxonomy', 'term']
[params]
  RecordingsBaseUrl = 'https://pavlov.photography/leonid-pavlov/audio-aac/'
[permalinks]
  recordings = "/recordings/:filename/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$']]